[package]
name = "pbyklib"
version = "0.2.1"
edition = "2021"
rust-version = "1.65"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64ct = { version="1.6.0", features = ["alloc"] }
# EnvelopedDataBuilder is not yet released, hence use of private branch
cms = {version = "0.2.1", git = "https://github.com/carl-wallace/formats.git", features = ["builder"], branch = "pbyk"}
const-oid = { version = "0.9.5", features = ["db"] }
der = { version = "0.7.8", features = ["alloc", "derive", "oid", "pem"] }
spki = "0.7.3"
x509-cert = "0.2.4"
# certval has not yet been released, hence use of private branch
certval = { git = "https://github.com/carl-wallace/rust-pki.git", features = ["std"], branch = "pbyk"}

aes = "0.8.3"
cipher = "0.4.4"
cbc = "0.1.2"
rsa = { version = "0.9.6", features = ["sha2"] }
sha-1 = {version = "0.10.1", default-features = false}
sha2 = "0.10.8"
signature = { version = "2.1.0", features = ["digest", "alloc"]}

hex-literal = "0.4.1"
lazy_static = "1.4.0"
log = "0.4.20"
plist = "1.6.0"
rand_core = { version = "0.6.4", features = ["std"] }
reqwest = {version = "0.11.22", features = ["rustls-tls", "multipart", "blocking"]}
serde = { version = "1.0.193", default-features = false, features = ["derive"] }
serde_json = "1.0.108"
subtle = { version = "2.5.0", default-features = false }
subtle-encoding = "0.5.1"
tokio = { version = "1.33.0", features = ["full", "time", "rt-multi-thread"]}
yubikey = { version = "0.8.0", features = ["untested"] }

# DO NOT ADVANCE OPENSSL CRATE BEYOND 0.10.55 UNTIL PORTAL IS NO LONGER USING RC2-40 (!).
# When this is updated, remove the old test cases that use RC2 in p12.rs.
# This also requires openssl-src on 111.26.0+1.1.1u and openssl-sys on 0.9.90,
openssl = {version = "0.10.55", features = ["vendored"]}
pkcs1 = "0.7.5"

[features]
default = ["dev"]
dev = []
om_nipr = []
om_sipr = []
nipr = []
sipr = []
