[package]
name = "pbyklib"
version = "0.3.0"
edition = "2021"
rust-version = "1.80.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64ct = { version="1.6.0", features = ["alloc"] }
# EnvelopedDataBuilder is not yet released, hence use of private branch
cms = {version = "0.2.1", git = "https://github.com/carl-wallace/formats.git", features = ["builder"], branch = "pbyk"}
pkcs12 = {version = "0.0.0", git = "https://github.com/carl-wallace/formats.git", branch = "pbyk"}
const-oid = { version = "0.9.5", features = ["db"] }
der = { version = "0.7.8", features = ["alloc", "derive", "oid", "pem"] }
spki = "0.7.3"
x509-cert = "0.2.5"
pkcs8 = { version = "0.10.2", features = ["pkcs5", "getrandom"] }
pkcs5 = {version = "0.7.1", features = ["pbes2", "3des"]}

# certval has not yet been released, hence use of private branch
certval = { git = "https://github.com/carl-wallace/rust-pki.git", features = ["std"]}

aes = "0.8.3"
cipher = "0.4.4"
cbc = "0.1.2"
pkcs1 = "0.7.5"
rsa = { version = "0.9.6", features = ["sha2"] }
sha-1 = {version = "0.10.1", default-features = false}
sha2 = "0.10.8"
signature = { version = "2.1.0", features = ["digest", "alloc"]}

hex-literal = "0.4.1"
home = "0.5.9"
log = "0.4.20"
plist = "1.6.0"
rand_core = { version = "0.6.4", features = ["std"] }
reqwest = {version = "0.12.4", features = ["rustls-tls", "multipart", "blocking"]}
serde = { version = "1.0.195", default-features = false, features = ["derive"] }
serde_json = "1.0.111"
subtle = { version = "2.5.0", default-features = false }
subtle-encoding = "0.5.1"
tokio = { version = "1.35.1", features = ["full", "time", "rt-multi-thread"]}
uuid = { version = "1.7.0", features = ["v4"] }
# the yubikey fork features a length check needed when pbyk is run in presence of some middleware. use fork until upstream is updated with length check added to form.
#yubikey = { version = "0.8.0", features = ["untested"] }
yubikey = {git = "https://github.com/carl-wallace/yubikey.rs.git", branch = "pbyk", features = ["untested"]}
zeroize = "1.7.0"

# DO NOT ADVANCE OPENSSL CRATE BEYOND 0.10.55 UNTIL PORTAL IS NO LONGER USING RC2-40 (!).
# When this is updated, remove the old test cases that use RC2 in p12.rs.
# This also requires openssl-src on 111.26.0+1.1.1u and openssl-sys on 0.9.90,
openssl = {version = "0.10.55", features = ["vendored"]}

pb_pki = {git="https://github.com/carl-wallace/pb_pki.git"}

[dev-dependencies]
log4rs = "1.3.0"

[target.'cfg(windows)'.dependencies]
windows = {version = "0.52", features = [
    "Devices_Enumeration", "Devices_SmartCards", "Foundation_Collections",
    "Security_Cryptography", "Security_Cryptography_Certificates", "Security_Cryptography_Core", "Security_ExchangeActiveSyncProvisioning",
    "Storage_Streams", "System_Profile",
    "Win32_Foundation", "Win32_Security", "Win32_Security_Cryptography"] }

[features]
default = ["dev"]
dev = ["pb_pki/dev"]
om_nipr = ["pb_pki/om_nipr"]
om_sipr = ["pb_pki/om_sipr"]
nipr = ["pb_pki/nipr"]
sipr = ["pb_pki/sipr"]
vsc = []
reset_vsc = [] # this feature exists to quarantine non-functional VSC reset code. do not use.
