[package]
name = "pbyk"
version = "0.1.0"
edition = "2021"
rust-version = "1.70"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pbyklib = {path = "../pbyklib"}

clap = {version = "4.4.7", features=["std", "derive"]}
colored = "2.0.4"
log = "0.4.17"
log4rs = {version = "1.2.0"}
rpassword = "7.2.0"
tokio = { version = "1.33.0", features = ["full", "time", "rt-multi-thread"]}
yubikey = { version = "0.8.0", features = ["untested"] }

[features]
default = ["dev"]
dev = ["pbyklib/dev"]
om_nipr = ["pbyklib/om_nipr"]
om_sipr = ["pbyklib/om_sipr"]
nipr = ["pbyklib/nipr"]
sipr = ["pbyklib/sipr"]