[package]
name = "pbyk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64ct = { version="1.6.0", features = ["alloc"] }
#cms = {version = "0.2.1", path = "../../../RustCrypto/formats-pr/cms", features = ["builder"]}
#cms = {version = "0.2.1", path = "../../../carl-wallace/formats/cms", features = ["builder"]}
cms = {version = "0.2.1", git = "https://github.com/carl-wallace/formats.git", features = ["builder"], branch = "cmsbuilder"}
const-oid = { version = "0.9", features = ["db"] }
der = { version = "0.7.6", features = ["alloc", "derive", "oid", "pem"] }
spki = "0.7.2"
x509-cert = "0.2.3"
yubikey = { version = "0.8.0-pre.0", git = "https://github.com/carl-wallace/yubikey.rs.git", features=["untested"], branch="x509_pr" }

pbyklib = {path = "../pbyklib"}

aes = "0.8.3"
cipher = "0.4.4"
cbc = "0.1.2"
rsa = { version = "0.9.2", features = ["sha2"] }
sha-1 = {version = "0.10.1", default-features = false}
sha2 = "0.10"
signature = { version = "2.1.0", features = ["digest", "alloc"]}

clap = {version = "4.3.4", features=["std", "derive"]}
hex-literal = "0.4.1"
log = "0.4.17"
log4rs = {version = "1.2.0"}
rpassword = "7.2.0"
reqwest = {version = "0.11", features = ["rustls-tls", "multipart", "blocking"]}
plist = "1.4.3"
serde = { version = "1.0.152", default-features = false, features = ["derive"] }
serde_json = "1.0.94"
subtle = { version = "2.1.1", default-features = false }
tokio = { version = "1.26.0", features = ["full", "time", "rt-multi-thread"]}
uuid = {version = "1.3.1", features = ["v4"]}

